[tool.black]
line-length = 100
target-version = ["py312"]
exclude = "/(\\.venv|build|dist|.pytest_cache)/"

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E","F","I"]
ignore = ["E203","E266","E501"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
