name: Melhoria de UI
description: Mudanças visuais padronizadas
title: "UI: "
labels: ["ui"]
body:
  - type: checkboxes
    attributes:
      label: Checklist UI
      options:
        - label: Títulos abóbora
        - label: Inputs 250px / gap 20px
        - label: Cabeçalhos abóbora centralizados
        - label: Data/Hora estreitas
        - label: Sem CSS fora de ui/
