name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt || true
      - run: python -V
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (app)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev tools
        run: |
          pip install black==24.8.0 ruff==0.5.6 isort==5.13.2 mypy==1.10.0 pytest==8.2.0

      - name: Black (format check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: isort (imports)
        run: isort . --check-only

      - name: mypy (type check)
        run: |
          mypy aplicativo.py db.py || true

      - name: pytest
        run: pytest -q || true
