name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:   # botão "Run workflow" manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt || true
      - run: python -V
