name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:   # permite rodar manualmente pelo botão "Run workflow"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt || true
      - run: python -V


      - name: Install dependencies (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: true
